### ISSUE TITLE
Using traits ans structures from the standard library

### ISSUE THREAD

**Issue by Vaelden** [dwrensha/capnproto-rust#19]
`capnproto-rust` redefines some traits / structures that seem to exist in the standard library, such as [BufferedReader](http://doc.rust-lang.org/std/io/struct.BufferedReader.html) and [BufferedWriter](http://doc.rust-lang.org/std/io/struct.BufferedWriter.html) and the corresponding wrappers, but with a few changes.

Is there a particular reason to redefine those traits and structures, such as an insufficent API or too much API instability? Or is it there more for legacy reasons?

**Comment by dwrensha** [comment]
Thanks to https://github.com/dwrensha/capnproto-rust/pull/41, we now do use the standard traits.
