### ISSUE TITLE
signature of `get_segments_for_output`

### ISSUE THREAD

**Issue by vks** [dwrensha/capnproto-rust#28]
Why does  `get_segments_for_output` take a function of the segments as an argument instead of just returning the segments?

**Comment by dwrensha** [comment]
Good question! I've cleaned this up in https://github.com/dwrensha/capnproto-rust/commit/cfecf2b4bee1ec7c8d8afe4310817d1c3837f5bd. The new signature is:

```
fn get_segments_for_output<'a>(&'a mut self) -> &'a[&'a[Word]] 
```

**Comment by vks** [comment]
Does this mean that I have to use mutable references to create a `SegmentArrayMessageReader` from a `MallocMessageBuilder`?

**Comment by dwrensha** [comment]
Yes, you'll need a mutable reference to the `MallocMessageBuilder`.

I just now wrote some documentation about this:
https://github.com/dwrensha/capnproto-rust/commit/90f09c7c561a2f1675bfeae6330b21d7c0403ba3

Hm, I think it wold be possible to avoid needing a mutable reference here, but it would involve doing more work on every call to `BuilderArena::allocate()`. I'm not sure whether it's worth it.

**Comment by vks** [comment]
I can think of one scenario: When storing data in capnproto's format (essentially using it like a native Rust struct) you may want to access the data from different threads, which could in theory work if readers were read-only.

**Comment by dwrensha** [comment]
I'm not sure that I understand what you're suggesting. Do you want to implement standard library traits on `MallocMessageBuilder`? Or on `foo::Builder<'a>` and `foo::Reader<'a>`, where `Foo` is a struct defined in a Cap'n Proto schema? In either these cases, I don't see how the signature of `get_segments_for_output()` makes a difference. Typically, a `MallocMessageBuilder` is passed around by value, which means that can always form either a mutable or an immutable reference to it.

**Comment by vks** [comment]
I want to build a struct that provides accessors to the underlying capnproto message, such that serialization is a noop.

To talk in terms of the address book example, something like
```rust
struct Adressbook {
    message: capnp::MallocMessageBuilder
}
[...]
fn main() {
    let adressbook = Adressbook::new(...);
    let people = adressbook.get_people();
    [...]
}
```
Then I want to implement `Debug`, `PartialEq` etc. on `Adressbook`.
I'm struggling with getting a `MessageReader` to work on top of the `MessageBuilder` without copying/allocating memory.

The problem with the `get_segments_for_output` signature is that I cannot use it for implementing the accessors (i.e. `get_people`), because they cannot mutate `self` if I want to use them for implementing the `std` traits.

I tried adding the segments to the struct to get around the `&mut` (which should be fine if the message is not modified after construction), but I couldn't make the lifetimes work.
