### ISSUE TITLE
Auto-generate and host docs!

### ISSUE THREAD

**Issue by Hoverbear** [dwrensha/capnproto-rust#29]
It'd be great if the documentation for the project was available online. You can easily integrate this into your CI automatically in the `.travis.yml` file if you are able to generate an application token and secure it.

I wrote about how to do this [here](http://www.hoverbear.org/2015/03/07/rust-travis-github-pages/#setupyourrepository), it should only take a few minutes if you already have the `travis` gem installed.

[The RPC repo](https://github.com/dwrensha/capnp-rpc-rust) could also benefit from this.

**Comment by dwrensha** [comment]
I had been hosting the docs [here](http://rust-ci.org/dwrensha/capnp-rpc-rust/doc/capnp/index.html) but it looks like that has failed to update for some time now. Eek!

I don't like the idea of hosting the docs with Github Pages. Last time I checked, the generated documentation was on the order of 10MB; if I bring those files into a git repo, it will probably grow large quite quickly.

Sadly, I can't read your blog post right now, as it looks like hoverbear.org is down.

**Comment by Hoverbear** [comment]
Odd, Nginx crashed... Fixed now.

There is currently no link to that documentation anywhere on the repository! :(

**Comment by dwrensha** [comment]
I just set up a permanent home for the documentation:
http://docs.capnproto-rust.org/

**Comment by dwrensha** [comment]
I've also added a `documentation = "http://docs.capnproto-rust.org"` entry to the Cargo configs, so once I publish the next releases the crates' pages on crates.io will link to the documentation.

**Comment by Hoverbear** [comment]
Awesome! Can we make sure that it's also present in the git repo somewhere? Not everyone views the Crates.io page.

**Comment by dwrensha** [comment]
(Note that the source links are currently broken due to https://github.com/rust-lang/rust/issues/23192.)

**Comment by dwrensha** [comment]
> Can we make sure that it's also present in the git repo somewhere?

Done: https://github.com/dwrensha/capnproto-rust/commit/ef316ef27d545a2c1a641b93e396cf8f430c201d

**Comment by Hoverbear** [comment]
@dwrensha You're the best!
