### ISSUE TITLE
Custom IO traits are problematic

### ISSUE THREAD

**Issue by danburkert** [dwrensha/capnproto-rust#32]
The `InputStream` and `OutputStream` traits closely mirror the functionality of the standard library's `Read` and `Write` traits, but they are less flexible.  In addition to having to wrap `Read` and `Write` instances, it makes it impossible to use a type that implements `Read` and `Write` (for example `TcpStream`) in separate `InputStreamWrapper` and `OutputStreamWrapper` instances.

I looked at replacing the uses of these traits with their standard library equivalent, or just providing default implementations of them for the standard library types, but it requires some changes to the deepest darkest parts of `serialize_packed`, so I got a bit scared off.

**Comment by dwrensha** [comment]
> it makes it impossible to use a type that implements Read and Write (for example TcpStream) in separate InputStreamWrapper and OutputStreamWrapper instances.

Can you clarify what you mean here? If I have `stream : TcpStream`, then I can  use any of `ReadInputStream::new(stream)`, `ReadInputStream::new(&mut stream)` or `ReadInputStream::new(try!(stream.try_clone())`, which I think covers most use cases.

**Comment by danburkert** [comment]
You are correct; `TcpStream` is a bad example since it is cloneable, and `&TcpStream` implements `Read` and `Write`.  The issue arrises for a type which has neither of those attributes.

`InputStream` and `OutputStream` are easily satisfied by the standard `Read` and `Write` traits (see [here](https://github.com/danburkert/capnproto-rust/tree/io-traits)), so my issue basically boils down to the fact that the wrapper types are required when they don't add any functionality.  Taking this line of reasoning to it's logical conclusion, the `InputStream` and `OutputStream` abstractions are not adding any value on top of `Read` and `Write`.

**Comment by dwrensha** [comment]
Ah, but they do add value! 

`Read::read()` and `Write::write()` are annoyingly ambiguous about when they are supposed to return. Is it after they've made at most one call to the underlying I/O object, as the [Write docs](http://doc.rust-lang.org/std/io/trait.Write.html) suggest? Well, not even `::std::io::BufWriter()` follows that rule.

In contrast, `InputStream::try_read()` and `OutputStream::write()` have clear contracts: `stream.try_read(buf, min_bytes)` returns on EOF or as soon as possible after `min_bytes` have been read, and `stream.write(buf)` always writes the whole buffer. These are the semantics that callers almost always want. In our case, the caller is quite often some outer object that is implementing the same interface.

As I see it, `Read` and `Write` basically describe operations on file descriptors, while `InputStream` and `OutputStream` are higher-level abstractions.

I think the blanket impls that you are suggesting (https://github.com/danburkert/capnproto-rust/commit/e6b51f999de2fcdaf4b05e8cda71e12b8fd02f68, https://github.com/danburkert/capnproto-rust/commit/04bcbeeb050130e0a9882c606220f19b03149ba6) might be a really good idea! I didn't know that was possible without getting a "conflicting implementations" error.  With those changes, clients would not have to worry about `InputStream` and `OutputStream` at all if they don't want to.

**Comment by dwrensha** [comment]
I've gone ahead and pulled those commits. Thanks!

**Comment by danburkert** [comment]
No problem, I think this is a good solution, thanks.
