### ISSUE TITLE
Segmentation fault while accessing `Text` from null capnp pointer

### ISSUE THREAD

**Issue by csherratt** [dwrensha/capnproto-rust#54]
You can follow a `null` capnp pointer. But if you try to access some fields in it (in my case a text field) it will trigger a segmentation fault. I'm not sure if the bug is accessing the field, or being able to follow the pointer in the first place.

Example of the bug: https://github.com/csherratt/capnp_crash

Backtrace:
```
#0  0x000055555557cf84 in capnp::private::endian::u32.Endian::get (self=0x0) at /home/colin/Source/capnproto-rust/src/private/endian.rs:52
#1  0x000055555557d679 in capnp::private::endian::WireValue<T>::get (self=0x0) at /home/colin/Source/capnproto-rust/src/private/endian.rs:29
#2  0x000055555557db39 in capnp::private::layout::WirePointer::is_null (self=0x0) at /home/colin/Source/capnproto-rust/src/private/layout.rs:322
#3  0x0000555555581048 in capnp::private::layout::wire_helpers::read_text_pointer (segment=0x0, reff=0x0, default_value=0x0, default_size=0)
    at /home/colin/Source/capnproto-rust/src/private/layout.rs:1773
#4  0x0000555555581eb2 in capnp::private::layout::PointerReader<'a>::get_text (self=0x7fffffffd5d8, default_value=0x0, default_size=0)
    at /home/colin/Source/capnproto-rust/src/private/layout.rs:1915
#5  0x000055555555c56d in capnp_crash::test_capnp::foo::Reader<'a>::get_txt (self=...) at target/debug/build/capnp_crash-d343ef91834373e5/out/test_capnp.rs:59
#6  0x000055555555cc0a in capnp_crash::main () at src/main.rs:26
#7  0x000055555558c7f5 in rt::unwind::try::try_fn::h9959899096596013704 ()
#8  0x000055555558a479 in __rust_try ()
#9  0x000055555558c4e0 in rt::lang_start::h46248b0221ecaad5blx ()
#10 0x000055555556ba67 in main ()
```

**Comment by dwrensha** [comment]
Thanks for the report and easily reproducible test case!
Fixed in https://github.com/dwrensha/capnproto-rust/commit/9a207cbe0acc691128b745a40c5b0662c0c3cc81 and tested in https://github.com/dwrensha/capnpc-rust/commit/a73ff53a6c2c9d593f9bd8176229a51acee59b71.

It'd be really cool if we could rewrite all of these unsafe internals in safe code. Someday...

**Comment by burdges** [comment]
Appears relevant : https://erickt.github.io/blog/2015/09/22/if-you-use-unsafe/

**Comment by dwrensha** [comment]
Yeah, I think we should be using compiletest. Unfortunately, I don't think it would have caught this particular bug.
