### ISSUE TITLE
Assert failure on broken file

### ISSUE THREAD

**Issue by octplane** [dwrensha/capnproto-rust#62]
Hello,

While playing with the lib, I opened a broken file and it crashed with an assert:

```
---- tests::broken_file stdout ----
	thread 'tests::broken_file' panicked at 'assertion failed: size > 0', /Users/octplane/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/capnp-0.7.0/src/serialize_packed.rs:101
stack backtrace:
   1:        0x104de2598 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:        0x104de4835 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:        0x104de43bf - std::panicking::default_hook::hc2c969e7453d080c
   4:        0x104dd9466 - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:        0x104d7b6d7 - std::sys_common::unwind::begin_unwind::h65390c63b501d6ed
   6:        0x104d80bb9 - _<capnp..serialize_packed..PackedRead<R> as std..io..Read>::read::h225fe399cdb1fa2c
```

You can checkout `https://github.com/octplane/kiosque` at tag `ISSUE_CAPNPROTORUST_BROKEN_FILE ` and run `cargo test broken_file`.

Schema is at https://github.com/octplane/kiosque/blob/ISSUE_CAPNPROTORUST_BROKEN_FILE/logformat/src/schema.capnp and guilty file is https://github.com/octplane/kiosque/blob/ISSUE_CAPNPROTORUST_BROKEN_FILE/broken/sample148.capnp

I suppose this should be recoverable in someway at the consumer level, hence this issue.

Thanks!

**Comment by dwrensha** [comment]
Thank you! Fixed in https://github.com/dwrensha/capnproto-rust/commit/61be723e0f1d65175282b2766d4e1b0411942aaa.

**Comment by dwrensha** [comment]
published https://crates.io/crates/capnp/0.7.1

**Comment by octplane** [comment]
Excellent, thanks !
