### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by maciejkula** [dwrensha/capnproto-rust#65]
Please, please add a basic example somewhere.

At the moment I have absolutely no idea how to use any of your stuff.

**Comment by dwrensha** [comment]
See https://github.com/dwrensha/capnpc-rust/tree/master/example/addressbook and https://github.com/dwrensha/capnp-rpc-rust/tree/master/examples . I suppose I should link to these in the README.

**Comment by maciejkula** [comment]
Fantastic, thanks!

**Comment by dwrensha** [comment]
Fixed in https://github.com/dwrensha/capnproto-rust/commit/dbea7103d2bd8081bf27653c2a641bb50525336e.
