### ISSUE TITLE
Why does initializing inner unions consume the parent builder

### ISSUE THREAD

**Issue by jteplitz602** [dwrensha/capnproto-rust#70]
If I have a schema like this
```
struct Foo {
  bar :union {
    // omitted
  }
}
```
the autogenerated code for `Foo::Builder` includes a method called `init_bar`, which consumes `Foo::Builder`. I'm new to rust, but this seems unideal to me for a couple reasons:

1. If Foo has other values I either have to set them before calling `init_bar` or I have to create another `Foo::Builder` from the containing buffer after setting up bar. 
2. If `Foo::Builder` is borrowed in the current scope I can't call `init_bar`

Was this intentional or is it a bug?

**Comment by dwrensha** [comment]
Hi!
This is intentional. [Here is a post](https://dwrensha.github.io/capnproto-rust/2014/12/27/custom-mutable-references.html) explaining the reasoning. TLDR, there should be a `foo::Builder::borrow()` method that you can use to make a temporary `foo::Builder` on which to call `init_bar()`.

**Comment by jteplitz602** [comment]
Ah, I see. Thanks!
